---
- hosts: aws-wp

  vars_files:
    - defaults/main.yml

  remote_user: "{{ system_user }}"
  become: yes
  gather_facts: no
  serial: 1

  vars_prompt:

    - name: domain
      prompt: "\n------
              \n\nSpecify WordPress URL"
      private: no
      default: "foolcontrol.org"

    - name: wp_version
      prompt: "\n------
              \n\nSpecify WordPress version you'd like to use"
      private: no
      default: "4.7.5"

    - name: wp_db_name
      prompt: "\n------
              \n\nSpecify WordPress database name"
      private: no
      default: "wordpress"

    - name: wp_db_tb_pre
      prompt: "\n------
              \n\nSpecify WordPress table prefix"
      private: no
      default: "wp_"

    - name: wp_db_psw
      prompt: "\n------
              \n\nSpecify WordPress database password"
      private: yes
      default: "C7@kM3"
      confirm: yes

  roles:
  - python
  - docker
  - wordpress-docker
